### ISSUE TITLE
SELINUX权限设置

### ISSUE THREAD

**Issue by dingchengshan** [weyo/mirrors#1]
您好：
我在执行SELINUX时出现如下bug
![image](https://user-images.githubusercontent.com/33179596/58616905-64b7b100-82f1-11e9-969b-a65f84e546c0.png)
请求帮助

**Comment by weyo** [comment]
SELINUX的配置问题，百度到的解决方法，供参考：https://www.linuxidc.com/Linux/2012-09/70199.htm
