### ISSUE TITLE
有试过只同步部分镜像么

### ISSUE THREAD

**Issue by ysicing** [weyo/mirrors#2]
从目前来看，好像是全量同步。例如debian系统我只需同步debian 9，ubuntu系统我只同步 18.04。绝大部分都用不上

**Comment by ysicing** [comment]
update: 暂时用Artifactory缓存解决了 🐶

**Comment by wondar-chan** [comment]
具体怎么解决的呢？方便说一下吗，我也有同样的需求，只同步ubuntu 18.04和ubuntu 20.04的

**Comment by ysicing** [comment]
@wondar-chan  使用缓存功能，nexus也能实现类似效果。
