### ISSUE TITLE
搭建二级镜像

### ISSUE THREAD

**Issue by lovechang1986** [weyo/mirrors#3]
你好，看到这个项目真的帮助很大。鉴于我目前的环境有下面问题想请教不知道方便解答吗？

清华tunasync所使用的镜像源都是官方源，我这边其实对实时性要求不高，只想做一个清华的二级源，是否直接按照您readme里面的教程将tunasync里面的各个py文件的源地址修改一下即可呢？

**Comment by lovechang1986** [comment]
您好，我按照您的教程想要做anaconda的镜像，遇到如下问题不知道您是如何解决的呢？

@ERROR: Unknown module 'anaconda'
rsync error: error starting client-server protocol (code 5) at main.c(1666) [Receiver=3.1.2]

**Comment by weyo** [comment]
自建一般都是使用二级源，比如清华、中科大提供的源，或者在网上搜下支持rsync的其他源都可以。这个问题可能是源没有配置好，建议可以去清华tunasync官方git项目下去咨询下。
